{% set name = "pygbx" %}
{% set version = "0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygbx-{{ version }}.tar.gz
  sha256: 83a944b91340e5738f196344c2a9a6d4485d020d7d64d61f03bb6718ca0b2212

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - python-lzo

test:
  imports:
    - pygbx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/donadigo/pygbx
  summary: A Python library to parse GBX files
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
